In [1]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

**Question 1 : Run the code in this section. Change the conditional statement X == Y in this section to X < Y or X > Y, and then see what kind of tensor you can get. **

In [2]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [3]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

**Question 2 : Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?**

In [4]:
a = torch.arange(3).reshape((3, 1, 1))
b = torch.arange(2).reshape((2, 1, 1))
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [5]:
a = torch.arange(3).reshape((3, 1, 1))
b = torch.arange(2).reshape((1, 2, 1))
a * b

tensor([[[0],
         [0]],

        [[0],
         [1]],

        [[0],
         [2]]])

**The dimensions to broadcast need to either be the same in both tensor, in all dimension or need to be one in not matching ones.**